### ISSUE TITLE
axilwr2wbsp.v does not define err_state

### ISSUE THREAD

**Issue by bchetwynd** [ZipCPU/wb2axip#4]
The axilwr2wbsp.v and axilrd2wbsp.v files define the err_state register after it is used.  Some tools (modelsim for example) does not support this.

**Comment by ZipCPU** [comment]
Fixed.

The problem was that err_state wasn't defined before being used.  It was still defined later in the file.

Yes, some tools don't support this.

The definition of err_state has been moved to the top of the file.  Unused values have also been removed.  The updated versions now pass a Verilator test, and still pass their formal test.

Dan
